### PR TITLE
 Improvements to R package installation procedure + fixes to R package structure

### PR DESCRIPTION
**Pull request by pcarbo**
Most significant changes: 

+ Improvements to `make rpackage` so that it is simpler and accommodates more R setups and platforms (e.g., now accepts customization of compiler options through `~/.R/Makevars`). Updated README to reflect these changes.

+ The `Makefile` inside the R package is now better aligned with R conventions (e.g., using the standard naming scheme for macros/variables). I also fixed up some other parts of the package to reduce the number of WARNINGS from `R CMD check`. 

+ Included additional installation help for Mac OS X, with recommendation to use Homebrew.

Thanks to @gaow and @jhmarcus for their help and in motivating these improvements.

### CODE REVIEW

**Comment by jobovy** [comment]
Thanks, this looks great! I don't use R, so have no way to test this, but if @gaow, who wrote the R wrapper, can sign off on this (sounds like you are working together), I'll merge this in.

**Comment by gaow** [comment]
Thanks a lot @jobovy and @pcarbo. I'll test and get back on this ticket!

**Comment by pcarbo** [comment]
I'm pulling in @jhmarcus on this since he is testing the R package installation as well.

**Comment by pcarbo** [comment]
@jobovy We verified the new R package installation steps on a couple of different laptops (Mac, Linux) and it works okay, so please go ahead and incorporate these changes into your master branch whenever you are ready.

**Comment by gaow** [comment]
@jobovy I have too tested it on 2 Linux machines without any issues.

**Comment by jobovy** [comment]
That's great, thanks for the thorough checking @pcarbo and @gaow. Will merge this now!

**Comment by pcarbo** [comment]
Wonderful, thank you.

**Pull request merged**
